const navBarCategoriesActionTypes = {
    GET_NAV_BAR_CATEGORIES__START: 'GET_NAV_BAR_CATEGORIES__START',
    GET_NAV_BAR_CATEGORIES__SUCCESS: 'GET_NAV_BAR_CATEGORIES__SUCCESS',
    GET_NAV_BAR_CATEGORIES__FAILURE: 'GET_NAV_BAR_CATEGORIES__FAILURE',
}

export default navBarCategoriesActionTypes;
