const productActionTypes = {
    GET_PRODUCT_BY_ID__START: 'GET_PRODUCT_BY_ID__START',
    GET_PRODUCT_BY_ID__SUCCESS: 'GET_PRODUCT_BY_ID__SUCCESS',
    GET_PRODUCT_BY_ID__FAILURE: 'GET_PRODUCT_BY_ID__FAILURE',
    SELECT_COLOR: 'SELECT_COLOR',
    SELECT_SIZE: 'SELECT_SIZE',
}

export default productActionTypes;
