const productActionTypes = {
    GET_PRODUCT_BY_ID__START: 'GET_PRODUCT_BY_ID__START',
    GET_PRODUCT_BY_ID__SUCCESS: 'GET_PRODUCT_BY_ID__SUCCESS',
    GET_PRODUCT_BY_ID__FAILURE: 'GET_PRODUCT_BY_ID__FAILURE',
    SELECT_COLOR: 'SELECT_COLOR',
    SELECT_SIZE: 'SELECT_SIZE',
    GET_PRODUCTS__START: 'GET_PRODUCTS__START',
    GET_PRODUCTS__SUCCESS: 'GET_PRODUCTS__SUCCESS',
    GET_PRODUCTS__FAILURE: 'GET_PRODUCTS__FAILURE',
    SELECT_REFINEMENT: 'SELECT_REFINEMENT',
    SELECT_SORTING_OPTION: 'SELECT_SORTING_OPTION',
    RESET_FILTERS: 'RESET_FILTERS',
}

export default productActionTypes;
