const productActionTypes = {
    GET_PRODUCT_BY_ID__START: 'GET_PRODUCT_BY_ID__START',
    GET_PRODUCT_BY_ID__SUCCESS: 'GET_PRODUCT_BY_ID__SUCCESS',
    GET_PRODUCT_BY_ID__FAILURE: 'GET_PRODUCT_BY_ID__FAILURE',
}

export default productActionTypes;
